project_id = "xrccsgxtwcopuxzofaey"

[functions.generate-video-access]
verify_jwt = true

[functions.strava-auth]
verify_jwt = true

[functions.strava-callback]
verify_jwt = false

[functions.strava-sync]
verify_jwt = true